### ISSUE TITLE
tarball's installation

### ISSUE THREAD

**Issue by OrianePourcelot** [CEDRICHK/smFishPlateDesigner#1]
![ErreurR](https://github.com/CEDRICHK/smFishPlateDesigner/assets/158067050/e08f3fb5-45c3-4256-b181-548f941529dc)

Hey du coup,
Voilà ce que j'obtiens, j'ai essayé de télécharger la version 4.2 et Rtools mais ça ne fonctionne pas

**Comment by CEDRICHK** [comment]
Erreur vient plutôt d'une dépendance non satisfaite. Essaie d'installer le package 'targets'.

**Comment by OrianePourcelot** [comment]
Okay je l'ai fait et ça a marché !
J'ai pu installé le package.

Mais je suis un peu perdue pour la suite. 
j'ai continué les instructions, et j'ai ouvert le script "_targets" mais si j'essaie de le lancer j'ai cette erreur :

![ErreurR2](https://github.com/CEDRICHK/smFishPlateDesigner/assets/158067050/1e40fa07-8a1c-4ac0-b434-e0cd512c3279)

**Comment by CEDRICHK** [comment]
Salut,

J'ajouterai les prérequis du coup comme les dépendances qui manque avant 
l'installation du package et l'utilisation du script R _targets.R. 
Lorsqu'on utilise le package smFishPlateDesigner les scripts.R ne sont 
plus disponibles, il faut donc, dans le script _targets.R, commenter la 
ligne via #

# source("R/functions.R)

ensuite

 > librairy(smFishPlateDesigner)
 > librairy(targets)
 > tar_make()

Je clos ce ticket sur l'installation du package. Si tu découvres 
d'autres bug, n'hésites pas à ouvrir un autre ticket.

Le 30/01/2024 à 10:33, OrianePourcelot a écrit :
> Okay je l'ai fait et ça a marché !
> J'ai pu installé le package.
>
> Mais je suis un peu perdue pour la suite.
> j'ai continué les instructions, et j'ai ouvert le script "_targets" mais si j'essaie de le lancer j'ai cette erreur :
>
> ![ErreurR2](https://github.com/CEDRICHK/smFishPlateDesigner/assets/158067050/1e40fa07-8a1c-4ac0-b434-e0cd512c3279)
>
>
>
>

-- 
Cédric HASSEN-KHODJA
Bio-Informaticien / Bio-Statisticien
MRI, Montpellier Ressources Imagerie
CRBM-CNRS
1919 route de Mende
34293 Montpellier
FRANCE
0434359721
