### ISSUE TITLE
Dossier ouput

### ISSUE THREAD

**Issue by OrianePourcelot** [CEDRICHK/smFishPlateDesigner#2]
Salut,
J'ai réglé le soucis que j'avais en précisant le path du script "functions.R" dans le script. 

Mais j'ai toujours un soucis.
Dans les instructions ça dit qu'il faut faire un dossier "output" pour les fichiers qui seront créés.
Mais je ne sais pas où le créer, ou bien où je dois noter le path.

HELP
Oriane

**Comment by CEDRICHK** [comment]
Salut,

Salut,
J'ai réglé le soucis que j'avais en précisant le path du script "functions.R" dans le script.

Normalement dans le package, tu n'as plus de functions.R. Tu as du 
récupérer le zip du github avec les fichiers sources.
Juste en commentant cette ligne ça devrait marcher.

Mais j'ai toujours un soucis.
Dans les instructions ça dit qu'il faut faire un dossier "output" pour les fichiers qui seront créés.
Mais je ne sais pas où le créer, ou bien où je dois noter le path.

Normalement à la racine de ton projet tu créés le dossier output. Dans 
ce dossier il y aura les résultats (les feuilles excels pour les 2 PCR, 
dosageTIV et FISH) si le workflow targets ne bug pas :-)

-- 
Cédric HASSEN-KHODJA
Bio-Informaticien / Bio-Statisticien
MRI, Montpellier Ressources Imagerie
CRBM-CNRS
1919 route de Mende
34293 Montpellier
FRANCE
0434359721


Le 31/01/2024 à 15:52, OrianePourcelot a écrit :
> Salut,
> J'ai réglé le soucis que j'avais en précisant le path du script "functions.R" dans le script.
>
> Mais j'ai toujours un soucis.
> Dans les instructions ça dit qu'il faut faire un dossier "output" pour les fichiers qui seront créés.
> Mais je ne sais pas où le créer, ou bien où je dois noter le path.
>
> HELP
> Oriane
>

**Comment by CEDRICHK** [comment]
Tu as eût le temps de vérifier. N'hésites pas à clore le ticket si c'est bon pour toi.
A+

**Comment by OrianePourcelot** [comment]
Hello,
Alors je n’ai toujours pas réussi à faire le faire fonctionner.
Je sais que je suis vraiment nulle en code du coup il faut vraiment me guider pas à pas et si je suis les instructions dans le read me ça ne donne que ça.
A+,
Oriane



De : CEDRICHK ***@***.***>
Envoyé : lundi 5 février 2024 17:41
À : CEDRICHK/smFishPlateDesigner ***@***.***>
Cc : Oriane Pourcelot ***@***.***>; Author ***@***.***>
Objet : Re: [CEDRICHK/smFishPlateDesigner] Dossier ouput (Issue #2)


Tu as eût le temps de vérifier. N'hésites pas à clore le ticket si c'est bon pour toi.
A+

**Comment by CEDRICHK** [comment]
Coucou, 

Tu es là pour ça, je vais améliorer le readme et corriger les bugs si besoin. N'hésites pas à m'appeler du coup pour que je puisse t'aider !

**Comment by OrianePourcelot** [comment]
Hello,

Donc j'ai réessayé de run après avoir ajouté un # à source("R/functions.R") dans _targets.R et cette fois-ci j'ai obtenu cette erreur :

 tar_make()
▶ dispatched target process_fish_data_without_primers
✖ errored target process_fish_data_without_primers
✖ errored pipeline [2.7 seconds]
Messages d'avis :
1: le package 'targets' a été compilé avec la version R 4.2.3 
2: le package 'tidyverse' a été compilé avec la version R 4.2.3 
3: le package 'ggplot2' a été compilé avec la version R 4.2.3 
4: le package 'tibble' a été compilé avec la version R 4.2.3 
5: le package 'readr' a été compilé avec la version R 4.2.3 
6: le package 'purrr' a été compilé avec la version R 4.2.3 
7: le package 'dplyr' a été compilé avec la version R 4.2.3 
8: le package 'lubridate' a été compilé avec la version R 4.2.3 
9: le package 'readxl' a été compilé avec la version R 4.2.3 
10: 1 targets produced warnings. Run targets::tar_meta(fields = warnings, complete_only = TRUE) for the messages. 
Error:
! Error running targets::tar_make()
Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
Debugging guide: https://books.ropensci.org/targets/debugging.html
How to ask for help: https://books.ropensci.org/targets/help.html
Last error message:
    impossible de trouver la fonction "processFishDataWithoutPrimers"
Last error traceback:
    .handleSimpleError(function (condition)  {     state$error <- build_mess...
    h(simpleError(msg, call))

Qu'est ce que je fais ?

**Comment by CEDRICHK** [comment]
Salut,, 

D'après le message il ne trouve pas la fonction processFishDataWithoutPrimers. Dans le script _targets.R, après 

`library(targets)` ajouter
`library(smFishPlateDesigner)` et ça devrait fonctionner !

A+

**Comment by OrianePourcelot** [comment]
Salut,

Je l'ai fait (et j'ai vérifié dans les packages) mais j'ai la même erreur qu'avant :

![Erreur](https://github.com/CEDRICHK/smFishPlateDesigner/assets/158067050/326fea21-00a5-44e3-8cbb-3e7808b7ef62)

**Comment by CEDRICHK** [comment]
bug résolu
